# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.motivo.com:587
mail_admin: admin@motivo.com
mail_hostname: motivo.com
mail_user: smtp_user
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml
